name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  site:
    uses: Roshann78/site-builder/.github/workflows/build.yml@main
    with:
      site_name: System Design
      domain: sysdesign.schrod1nger.me
